name: test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    name: build / node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 16.x, 18.x, 20.x, 22.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps (npm ci)
        run: npm ci

      - name: Type-check
        run: npm run check

      - name: Build
        run: npm run build

      - name: Verify dist files exist
        run: |
          test -f dist/index.js
          test -f dist/index.d.ts
          test -f dist/presets.js
          test -f dist/presets.d.ts

      - name: Smoke test (require compiled output)
        run: node -e "const m=require('./dist'); console.log('exports:', Object.keys(m))"

      - name: Pack (dry-run)
        run: npm pack --dry-run

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node }}
          path: |
            dist/**
            *.tgz
          if-no-files-found: error

  audit:
    name: audit (high+)
    runs-on: ubuntu-latest
    continue-on-error: true   # non blocca le PR se ci sono advisory transitive
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm audit --audit-level=high
